[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.6",
    "gunicorn>=23.0.0",
    "psycopg[binary,pool]>=3.2.5",
    "whitenoise>=6.9.0",
]
